# LOGISTICS REGRESSION

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import StandardScaler   
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report  

In [2]:
dataset=pd.read_csv(r"C:\Users\rocky\Desktop\ML CSV\Education Dataset.csv")

In [3]:
dataset

Marital status  Application mode  Application order  Course  \
0                  1                 8                  5       2   
1                  1                 6                  1      11   
2                  1                 1                  5       5   
3                  1                 8                  2      15   
4                  2                12                  1       3   
...              ...               ...                ...     ...   
4419               1                 1                  6      15   
4420               1                 1                  2      15   
4421               1                 1                  1      12   
4422               1                 1                  1       9   
4423               1                 5                  1      15   

      Daytime/evening attendance  Previous qualification  Nacionality  \
0                              1                       1            1   
1                              1                       1            1   
2                              1                       1            1   
3                              1                       1            1   
4                              0                       1            1   
...                          ...                     ...          ...   
4419                           1                       1            1   
4420                           1                       1           19   
4421                           1                       1            1   
4422                           1                       1            1   
4423                           1                       1            9   

      Mother's qualification  Father's qualification  Mother's occupation  \
0                         13                      10                    6   
1                          1                       3                    4   
2                         22                      27                   10   
3                         23                      27                    6   
4                         22                      28                   10   
...                      ...                     ...                  ...   
4419                       1                       1                    6   
4420                       1                       1                   10   
4421                      22                      27                   10   
4422                      22                      27                    8   
4423                      23                      27                    6   

      ...  Curricular units 2nd sem (credited)  \
0     ...                                    0   
1     ...                                    0   
2     ...                                    0   
3     ...                                    0   
4     ...                                    0   
...   ...                                  ...   
4419  ...                                    0   
4420  ...                                    0   
4421  ...                                    0   
4422  ...                                    0   
4423  ...                                    0   

      Curricular units 2nd sem (enrolled)  \
0                                       0   
1                                       6   
2                                       6   
3                                       6   
4                                       6   
...                                   ...   
4419                                    6   
4420                                    6   
4421                                    8   
4422                                    5   
4423                                    6   

      Curricular units 2nd sem (evaluations)  \
0                                          0   
1                                          6   
2                                          0   
3                                        

In [4]:
cols=['Target']

In [5]:
dataset[cols] = dataset[cols].apply(LabelEncoder().fit_transform)

In [6]:
dataset

Marital status  Application mode  Application order  Course  \
0                  1                 8                  5       2   
1                  1                 6                  1      11   
2                  1                 1                  5       5   
3                  1                 8                  2      15   
4                  2                12                  1       3   
...              ...               ...                ...     ...   
4419               1                 1                  6      15   
4420               1                 1                  2      15   
4421               1                 1                  1      12   
4422               1                 1                  1       9   
4423               1                 5                  1      15   

      Daytime/evening attendance  Previous qualification  Nacionality  \
0                              1                       1            1   
1                              1                       1            1   
2                              1                       1            1   
3                              1                       1            1   
4                              0                       1            1   
...                          ...                     ...          ...   
4419                           1                       1            1   
4420                           1                       1           19   
4421                           1                       1            1   
4422                           1                       1            1   
4423                           1                       1            9   

      Mother's qualification  Father's qualification  Mother's occupation  \
0                         13                      10                    6   
1                          1                       3                    4   
2                         22                      27                   10   
3                         23                      27                    6   
4                         22                      28                   10   
...                      ...                     ...                  ...   
4419                       1                       1                    6   
4420                       1                       1                   10   
4421                      22                      27                   10   
4422                      22                      27                    8   
4423                      23                      27                    6   

      ...  Curricular units 2nd sem (credited)  \
0     ...                                    0   
1     ...                                    0   
2     ...                                    0   
3     ...                                    0   
4     ...                                    0   
...   ...                                  ...   
4419  ...                                    0   
4420  ...                                    0   
4421  ...                                    0   
4422  ...                                    0   
4423  ...                                    0   

      Curricular units 2nd sem (enrolled)  \
0                                       0   
1                                       6   
2                                       6   
3                                       6   
4                                       6   
...                                   ...   
4419                                    6   
4420                                    6   
4421                                    8   
4422                                    5   
4423                                    6   

      Curricular units 2nd sem (evaluations)  \
0                                          0   
1                                          6   
2                                          0   
3                                        

In [7]:
x=dataset.iloc[:,1:34].values
y=dataset.iloc[:,34].values

In [8]:
print(x)
print(y)

[[ 8.    5.    2.   ... 10.8   1.4   1.74]
 [ 6.    1.   11.   ... 13.9  -0.3   0.79]
 [ 1.    5.    5.   ... 10.8   1.4   1.74]
 ...
 [ 1.    1.   12.   ... 13.9  -0.3   0.79]
 [ 1.    1.    9.   ...  9.4  -0.8  -3.12]
 [ 5.    1.   15.   ... 12.7   3.7  -1.7 ]]
[0 2 0 ... 0 2 2]


# LOGISTIC REGRESSION

In [9]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)

In [10]:
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)  

In [11]:
classifier= LogisticRegression(random_state=0)  
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [12]:
y_pred=classifier.predict(x_test)

In [13]:
print('accuracy score is ',accuracy_score(y_test,y_pred)*100)

accuracy score is  78.39059674502712


In [14]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.77      0.79       353
           1       0.58      0.37      0.45       193
           2       0.81      0.94      0.87       560

    accuracy                           0.78      1106
   macro avg       0.73      0.69      0.70      1106
weighted avg       0.77      0.78      0.77      1106



# NAIVE BAYES CLASSIFIER

In [15]:
from sklearn.naive_bayes import GaussianNB

In [16]:
classifier = GaussianNB()

In [17]:
classifier.fit(x_train,y_train)

GaussianNB()

In [18]:
y_pred=classifier.predict(x_test)

In [19]:
confusionmatrix=confusion_matrix(y_test,y_pred)

In [20]:
print(confusionmatrix)

[[239  43  71]
 [ 37  33 123]
 [ 31  47 482]]


In [21]:
print('accuracy score',accuracy_score(y_test,y_pred)*100)

accuracy score 68.1735985533454


In [22]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.68      0.72       353
           1       0.27      0.17      0.21       193
           2       0.71      0.86      0.78       560

    accuracy                           0.68      1106
   macro avg       0.59      0.57      0.57      1106
weighted avg       0.66      0.68      0.66      1106



# K-NEAREST NEIGHBOUR

In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
classifier=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [25]:
y_pred=classifier.predict(x_test)

In [26]:
conmax=confusion_matrix(y_test,y_pred)

In [27]:
print(conmax)

[[241  47  65]
 [ 57  47  89]
 [ 31  41 488]]


In [28]:
print('the accuracy score',accuracy_score(y_test,y_pred)*100)

the accuracy score 70.16274864376129


In [29]:
print('the classification report',classification_report(y_test,y_pred))

the classification report               precision    recall  f1-score   support

           0       0.73      0.68      0.71       353
           1       0.35      0.24      0.29       193
           2       0.76      0.87      0.81       560

    accuracy                           0.70      1106
   macro avg       0.61      0.60      0.60      1106
weighted avg       0.68      0.70      0.69      1106

