In [158]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import StandardScaler   
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [159]:
dataset=pd.read_csv(r"C:\Users\rocky\Desktop\ML CSV\Covid Dataset.csv")

In [160]:
dataset

Breathing Problem Fever Dry Cough Sore throat Running Nose Asthma  \
0                  Yes   Yes       Yes         Yes          Yes     No   
1                  Yes   Yes       Yes         Yes           No    Yes   
2                  Yes   Yes       Yes         Yes          Yes    Yes   
3                  Yes   Yes       Yes          No           No    Yes   
4                  Yes   Yes       Yes         Yes          Yes     No   
...                ...   ...       ...         ...          ...    ...   
5429               Yes   Yes        No         Yes          Yes    Yes   
5430               Yes   Yes       Yes          No          Yes    Yes   
5431               Yes   Yes       Yes          No           No     No   
5432               Yes   Yes       Yes          No          Yes     No   
5433               Yes   Yes       Yes          No          Yes    Yes   

     Chronic Lung Disease Headache Heart Disease Diabetes  ... Fatigue   \
0                      No       No            No      Yes  ...      Yes   
1                     Yes      Yes            No       No  ...      Yes   
2                     Yes      Yes            No      Yes  ...      Yes   
3                      No       No           Yes      Yes  ...       No   
4                     Yes      Yes           Yes      Yes  ...       No   
...                   ...      ...           ...      ...  ...      ...   
5429                  Yes       No            No       No  ...      Yes   
5430                   No      Yes            No      Yes  ...      Yes   
5431                   No       No           Yes       No  ...       No   
5432                   No      Yes           Yes       No  ...       No   
5433                   No      Yes            No      Yes  ...      Yes   

     Gastrointestinal  Abroad travel Contact with COVID Patient  \
0                  Yes            No                        Yes   
1                   No            No                         No   
2                  Yes           Yes                         No   
3                   No           Yes                         No   
4                  Yes            No                        Yes   
...                ...           ...                        ...   
5429               Yes            No                         No   
5430                No            No                         No   
5431                No            No                         No   
5432                No            No                         No   
5433                No            No                         No   

     Attended Large Gathering Visited Public Exposed Places  \
0                          No                           Yes   
1                         Yes                           Yes   
2                          No                            No   
3                         Yes                           Yes   
4                          No                           Yes   
...                       ...                           ...   
5429                       No                            No   
5430                       No                            No   
5431                       No                            No   
5432                       No                            No   
5433                       No                            No   

     Family working in Public Exposed Places Wearing Masks  \
0                                        Yes            No   
1                                         No            No   
2                                         No            No   
3                                         No            No   
4                                         No            No   
...                                      ...           ...   
5429                                      No            No   
5430                                      No            No   
5431                                      No            No   
5432                             

In [161]:
dataset = dataset.apply(LabelEncoder().fit_transform)

In [162]:
dataset

Breathing Problem  Fever  Dry Cough  Sore throat  Running Nose  Asthma  \
0                     1      1          1            1             1       0   
1                     1      1          1            1             0       1   
2                     1      1          1            1             1       1   
3                     1      1          1            0             0       1   
4                     1      1          1            1             1       0   
...                 ...    ...        ...          ...           ...     ...   
5429                  1      1          0            1             1       1   
5430                  1      1          1            0             1       1   
5431                  1      1          1            0             0       0   
5432                  1      1          1            0             1       0   
5433                  1      1          1            0             1       1   

      Chronic Lung Disease  Headache  Heart Disease  Diabetes  ...  Fatigue   \
0                        0         0              0         1  ...         1   
1                        1         1              0         0  ...         1   
2                        1         1              0         1  ...         1   
3                        0         0              1         1  ...         0   
4                        1         1              1         1  ...         0   
...                    ...       ...            ...       ...  ...       ...   
5429                     1         0              0         0  ...         1   
5430                     0         1              0         1  ...         1   
5431                     0         0              1         0  ...         0   
5432                     0         1              1         0  ...         0   
5433                     0         1              0         1  ...         1   

      Gastrointestinal   Abroad travel  Contact with COVID Patient  \
0                     1              0                           1   
1                     0              0                           0   
2                     1              1                           0   
3                     0              1                           0   
4                     1              0                           1   
...                 ...            ...                         ...   
5429                  1              0                           0   
5430                  0              0                           0   
5431                  0              0                           0   
5432                  0              0                           0   
5433                  0              0                           0   

      Attended Large Gathering  Visited Public Exposed Places  \
0                            0                              1   
1                            1                              1   
2                            0                              0   
3                            1                              1   
4                            0                              1   
...                        ...                            ...   
5429                         0                              0   
5430                         0                              0   
5431                         0                              0   
5432                         0                              0   
5433                         0                              0   

      Family working in Public Exposed Places  Wearing Masks  \
0                                           1              0   
1                                           0              0   
2                                           0              0   
3                                           0              0   
4                                           0              0   
...                                       ...            ...   
5429          

In [163]:
x=dataset.iloc[:,1:19].values
y=dataset.iloc[:,20].values

In [164]:
print(x)
print(y)

[[1 1 1 ... 1 1 0]
 [1 1 1 ... 1 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]]
[1 1 1 ... 0 0 0]


# LOGISTIC REGRESSION

In [165]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25,random_state=0)

In [166]:
len(x_train)

4075

In [167]:
len(x_test)

1359

In [168]:
classifier= LogisticRegression(random_state=0)  
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [169]:
y_pre=classifier.predict(x_test)

In [170]:
cm= confusion_matrix(y_test,y_pre)

In [171]:
print(cm)

[[ 235   26]
 [  30 1068]]


In [172]:
score=(accuracy_score(y_test,y_pre)*100)

In [173]:
score

95.87932303164092

# NAIVE BAYES CLASSIFIER

In [174]:
from sklearn.naive_bayes import GaussianNB

In [175]:
classifier = GaussianNB()

In [176]:
classifier.fit(x_train,y_train)

GaussianNB()

In [177]:
y_pre=classifier.predict(x_test)

In [178]:
confusionmatrix=confusion_matrix(y_test,y_pre)

In [179]:
print(confusionmatrix)

[[261   0]
 [350 748]]


In [180]:
scoreNB=(accuracy_score(y_test,y_pre)*100)

In [181]:
scoreNB

74.2457689477557

In [182]:
NBC=print(classification_report(y_test,y_pre))

              precision    recall  f1-score   support

           0       0.43      1.00      0.60       261
           1       1.00      0.68      0.81      1098

    accuracy                           0.74      1359
   macro avg       0.71      0.84      0.70      1359
weighted avg       0.89      0.74      0.77      1359



# KNN

In [183]:
from sklearn.neighbors import KNeighborsClassifier

In [184]:
classifier=KNeighborsClassifier(n_neighbors=5,metric='euclidean',p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean')

In [185]:
y_prediction=classifier.predict(x_test)

C:\Users\rocky\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [186]:
conmax=confusion_matrix(y_test,y_prediction)

In [187]:
print(conmax)

[[ 242   19]
 [  20 1078]]


In [188]:
scoreKNN=(accuracy_score(y_test,y_prediction)*100)

In [189]:
scoreKNN

97.13024282560706

In [190]:
print(classification_report(y_test,y_prediction))

              precision    recall  f1-score   support

           0       0.92      0.93      0.93       261
           1       0.98      0.98      0.98      1098

    accuracy                           0.97      1359
   macro avg       0.95      0.95      0.95      1359
weighted avg       0.97      0.97      0.97      1359



# SVM

In [191]:
from sklearn.svm import SVC

In [192]:
SVMclassifier = SVC(kernel = 'linear', random_state = 0)
SVMclassifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [193]:
y_pred = SVMclassifier.predict(x_test)

In [194]:
from sklearn import metrics

In [195]:
cm = metrics.confusion_matrix(y_test, y_pred)
print(cm)

[[ 237   24]
 [  30 1068]]


In [196]:
SVM_acc1 = metrics.accuracy_score(y_test, y_pred)
scoreSVM=(SVM_acc1*100)

In [197]:
scoreSVM

96.02649006622516